name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies for Api project
      run: dotnet restore src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj

    - name: Build Api project
      run: dotnet build --no-restore src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj

    - name: Test Api project
      run: dotnet test --no-build --verbosity normal src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj

    - name: Install xmlstarlet
      run: sudo apt-get update && sudo apt-get install -y xmlstarlet

    - name: Update package version
      run: xmlstarlet ed --inplace -u '//Version' -v '1.0.1' src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj


    - name: Generate NuGet packages
      run: |
        dotnet pack src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj --output nupkgs
        ls nupkgs # List the contents of the output directory to verify that packages were generated

    - name: Publish package
      run: |
        dotnet nuget push nupkgs/*.nupkg \
          --source "https://nuget.pkg.github.com/ythrinathareddy/index.json" \
          --api-key ${{ secrets.DotNet_Token }} \
          --skip-duplicate

    - name: Archive NuGet packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: nupkgs

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages

    - name: Create destination directory
      run: mkdir -p $HOME/packages

    - name: Extract NuGet packages
      run: tar -xvf nuget-packages.zip -C $HOME/packages/
